# Generated by Django 4.2.23 on 2025-10-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200, verbose_name='Título o Detalle')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reuniones/', verbose_name='Imagen (Opcional)')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
            },
        ),
    ]
