# Generated by Django 4.2.23 on 2025-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_etiqueta_emojis'),
        ('paneladm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='reuniones_asistidas', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección (Opcional)'),
        ),
    ]
