# Generated by Django 4.2.23 on 2025-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneladm', '0002_reunion_asistentes_reunion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
