# Generated by Django 4.2.23 on 2025-10-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneladm', '0003_reunion_latitud_reunion_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='longitud',
        ),
    ]
