# Generated by Django 4.2.23 on 2025-10-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_cantidad_asistencias'),
        ('paneladm', '0004_remove_reunion_direccion_remove_reunion_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Encuesta de Satisfacción', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Los usuarios solo pueden ver y responder encuestas activas.')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='paneladm.reunion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1 - Muy Malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='paneladm.encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuesta', to='usuario.usuario')),
            ],
            options={
                'unique_together': {('encuesta', 'usuario')},
            },
        ),
    ]
