# Generated by Django 4.2.23 on 2025-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_cantidad_asistencias'),
        ('paneladm', '0005_encuesta_respuestaencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='interesados',
            field=models.ManyToManyField(blank=True, related_name='reuniones_interesado', to='usuario.usuario'),
        ),
    ]
