# Generated by Django 4.2.23 on 2025-10-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneladm', '0006_reunion_interesados'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar como testimonio en la página de inicio.'),
        ),
    ]
