# Generated by Django 4.2.23 on 2025-10-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_cantidad_asistencias'),
        ('paneladm', '0008_soporteticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='paneladm.soporteticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
