# Generated by Django 4.2.23 on 2025-10-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneladm', '0009_ticketrespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrespuesta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='soporte_respuestas/', verbose_name='Imagen Adjunta'),
        ),
    ]
