# Generated by Django 4.2.23 on 2025-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneladm', '0010_ticketrespuesta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='imprimir_etiqueta_al_asistir',
            field=models.BooleanField(default=True, help_text='Si se marca, se abrirá la ventana para imprimir la etiqueta del asistente al escanear su QR.', verbose_name='¿Imprimir etiqueta al escanear QR?'),
        ),
    ]
