"""
Django settings for Ecosistema project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# --- Rutas del Proyecto (usando pathlib, que es más moderno) ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Configuración de Seguridad ---
SECRET_KEY = 'django-insecure-it)h7wo8um6o+%f+p8qduxi0p9)u7x(#zvh5k)_bj*n6wb!=p)'

# CAMBIO 1: DEBUG = True para desarrollo local. Esto es lo más importante.
# Hace que Django muestre errores detallados y sirva archivos estáticos.
DEBUG = True

# CAMBIO 2: En desarrollo, puedes dejar ALLOWED_HOSTS vacío o con los hosts locales.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Esto no es necesario para desarrollo local.
# CSRF_TRUSTED_ORIGINS = [
#     "https://meetingup.cl/",
#     "https://www.meetingup.cl/",
# ]

# CAMBIO 3: La URL base para desarrollo local.
BASE_URL = 'http://127.0.0.1:8000'

# --- Aplicaciones Instaladas ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuario',
    # 'login', # NOTA: La lógica de login parece estar en la app 'usuario', quizás esta app 'login' no es necesaria.
    'paneladm',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'usuario.middleware.UserInfoMiddleware', # Si no usas este middleware, puedes comentarlo.
]

ROOT_URLCONF = 'Ecosistema.urls'

# --- Plantillas ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Usando pathlib
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuario.context_processors.notificaciones_admin',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecosistema.wsgi.application'

# --- Base de Datos ---
# CAMBIO 4: Usaremos SQLite para desarrollo local. Es un solo archivo y no requiere instalación.
# Tu configuración de MySQL está bien si tienes MySQL instalado y configurado, pero SQLite es más simple para empezar.

# Si prefieres seguir usando MySQL, asegúrate de que el servidor MySQL esté corriendo.
# Tu configuración original para MySQL:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecola',          # La base de datos que creaste en el Paso 3.
        'USER': 'root',           # El usuario de tu MySQL (suele ser 'root' en local).
        'PASSWORD': '',           # La contraseña de tu usuario (suele estar vacía en XAMPP).
        'HOST': '127.0.0.1',      # El servidor local.
        'PORT': '3306',           # El puerto estándar de MySQL.
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4'
        }
    }
}

# --- Validación de Contraseñas ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internacionalización ---
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# --- Archivos Estáticos y de Medios ---
# CAMBIO 5: Configuración simplificada y clara para estáticos y medios.

# URL para acceder a los archivos estáticos (CSS, JS, imágenes del tema)
STATIC_URL = 'static/'
# Directorio donde `collectstatic` pondrá los archivos para producción. No se usa mucho con DEBUG=True.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Directorios donde Django buscará tus archivos estáticos personales.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# URL para acceder a los archivos subidos por los usuarios (fotos de perfil, etc.)
MEDIA_URL = '/media/'
# Directorio donde se guardarán los archivos subidos por los usuarios.
MEDIA_ROOT = BASE_DIR / 'media'


# --- Tipo de Clave Primaria por Defecto ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
