# Generated by Django 4.2.23 on 2025-10-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
