# Generated by Django 4.2.23 on 2025-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='etiqueta_emojis',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
