# Generated by Django 4.2.23 on 2025-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_etiqueta_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cantidad_asistencias',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Asistencias'),
        ),
    ]
