# Generated by Django 4.2.23 on 2025-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_cantidad_asistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil_publico',
            field=models.BooleanField(default=True, help_text='Permite que otros miembros vean tu perfil en el directorio.'),
        ),
    ]
