# Generated by Django 4.2.23 on 2025-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_perfil_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='buscando',
            field=models.CharField(blank=True, help_text='Ej: Inversionistas, socios, clientes, etc.', max_length=255, null=True, verbose_name='¿Qué buscas en la comunidad?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion_empresa',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Empresa/Pyme'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rubro_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro de la Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='web_empresa',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web de la Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rubro',
            field=models.CharField(blank=True, help_text='Tu profesión o área de expertise.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
