# Generated by Django 4.2.23 on 2025-10-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_email_verificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_verificado',
        ),
    ]
