# Generated by Django 4.2.23 on 2025-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_usuario_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
