# Generated by Django 4.2.23 on 2025-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rubro_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar otro rubro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rubro',
            field=models.CharField(blank=True, choices=[('Tecnología y Desarrollo', (('desarrollo_software', 'Desarrollo de Software'), ('desarrollo_web', 'Desarrollo Web'), ('desarrollo_movil', 'Desarrollo Móvil'), ('ia_machine_learning', 'Inteligencia Artificial / Machine Learning'), ('ciberseguridad', 'Ciberseguridad'), ('analisis_datos', 'Análisis de Datos / Big Data'), ('devops', 'DevOps'), ('infraestructura_cloud', 'Infraestructura y Cloud'), ('ecommerce', 'E-commerce'))), ('Diseño y Creatividad', (('diseno_grafico', 'Diseño Gráfico'), ('diseno_ux_ui', 'Diseño UX/UI'), ('produccion_audiovisual', 'Producción Audiovisual'), ('fotografia', 'Fotografía'), ('marketing_digital', 'Marketing Digital'), ('redes_sociales', 'Gestión de Redes Sociales'), ('publicidad', 'Publicidad'))), ('Negocios y Consultoría', (('consultoria_negocios', 'Consultoría de Negocios'), ('finanzas_contabilidad', 'Finanzas y Contabilidad'), ('recursos_humanos', 'Recursos Humanos'), ('ventas_desarrollo_negocios', 'Ventas y Desarrollo de Negocios'), ('legal_asesoria', 'Legal y Asesoría'), ('gestion_proyectos', 'Gestión de Proyectos'))), ('Salud y Bienestar', (('salud_medicina', 'Salud y Medicina'), ('psicologia_coaching', 'Psicología y Coaching'), ('nutricion', 'Nutrición'), ('deporte_fitness', 'Deporte y Fitness'))), ('Otros Sectores', (('educacion', 'Educación y Formación'), ('inmobiliario', 'Sector Inmobiliario'), ('turismo_hoteleria', 'Turismo y Hotelería'), ('gastronomia', 'Gastronomía'), ('construccion_arquitectura', 'Construcción y Arquitectura'), ('agroindustria', 'Agroindustria'), ('otro', 'Otro')))], help_text='Tu profesión o área de expertise.', max_length=100, null=True, verbose_name='Rubro'),
        ),
    ]
