# Generated by Django 4.2.23 on 2025-10-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_usuario_rubro_otro_alter_usuario_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_ayudante',
            field=models.BooleanField(default=False),
        ),
    ]
