# Generated by Django 4.2.23 on 2025-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_es_ayudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_totem',
            field=models.BooleanField(default=False, help_text='Designa a este usuario como una cuenta para un quiosco/tótem de check-in.'),
        ),
    ]
